config/routes.rb
Rails.application.routes.draw do

  #root
  get '/', to: 'shelters#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/shelters', to: 'shelters#index'
  get '/shelters/new', to: 'shelters#new'
  get '/shelters/:id/reviews/new', to: 'reviews#new'
  post '/shelters/:shelter_id/reviews', to: 'reviews#create'
  get '/shelters/:shelter_id/reviews/:review_id/edit', to: 'reviews#edit'
  patch '/shelters/:shelter_id/reviews/:review_id/', to: 'reviews#update'
  delete '/shelters/:shelter_id/reviews/:review_id/', to: 'reviews#destroy'
  post '/shelters', to: 'shelters#create'
  get '/shelters/:id', to: 'shelters#show'
  get '/shelters/:id/pets', to: 'shelters#pets'
  get '/shelters/:id/pets/new', to: 'pets#new'
  get '/shelters/:id/edit', to: 'shelters#edit'
  patch '/shelters/:id', to: 'shelters#update'
  delete '/shelters/:id', to: 'shelters#destroy'

  # resources :shelters
  get '/pets', to: 'pets#index'
  get '/pets/:id', to: "pets#show"
  get '/pets/:id/edit', to: 'pets#edit'
  post '/shelters/:shelter_id/pets/new', to: 'pets#create'
  patch '/pets/:id/edit', to: 'pets#update'
  delete '/pets/:id', to: "pets#destroy"
  get '/pets/:pet_id/adoptions', to: 'adoptions#index'
  patch '/pets/:pet_id/adoptions/:adoption_id', to: 'adoptions#update'

  get '/favorites', to: 'favorites#index'
  patch '/favorites/:pet_id', to: 'favorites#update'
  delete '/favorites', to: 'favorites#destroy_all'

  get '/adoptions/new', to: 'adoptions#new'
  get '/adoptions/:id', to: 'adoptions#show'
  post '/adoptions', to: 'adoptions#create'
end

app/models/favorites.rb
class Favorites
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || Array.new
  end

  def total_count
    contents.length
  end

  def add_pet(id)
    contents << id
  end

  def delete_favorites(pet_ids)
    pet_ids.each do |id|
      contents.delete(id.to_i)
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  include ActionView::Helpers::TextHelper

  def update
    # require "pry"; binding.pry
    if params[:remove]
      pet = Pet.find(params[:pet_id])
      session[:favorites] = favorites.contents
      favorites.contents.delete(pet.id)
      flash[:notice] = "#{pet.name} has been removed from your Favorites."
      redirect_back(fallback_location: "/pets")
    else
      pet = Pet.find(params[:pet_id])
      favorites.add_pet(pet.id)
      session[:favorites] = favorites.contents
      flash[:notice] = "#{pet.name} is now in your Favorites."
      redirect_to "/pets/#{pet.id}"
    end
  end

  def index
    # require "pry"; binding.pry
    apps = AdoptionPet.all
    @app_pets = []
    if !apps.nil?
      apps.each do |app|
        @app_pets << Pet.find(app[:pet_id])
      end
    end
    @app_pets.uniq
    if session[:favorites] == nil || session[:favorites].empty?
      @pets = nil
    else
      @pets = Pet.find(session[:favorites])
    end
  end

  def destroy_all
    # require "pry"; binding.pry
    session[:favorites] = favorites.contents
    favorites.contents.clear
    flash[:notice] = "Your Favorites list has been cleared."
    redirect_back(fallback_location: "/pets")
  end
end

app/views/favorites/index.html.erb
<body>
  <%= link_to "Back to Shelters", shelters_path %><br>
  <%= link_to "Back to Pets", pets_path %><br>
  <%= button_to "Remove All Favorites", "/favorites", method: :delete %>

<h1>Favorites List</h1>
<section id="list_of_favorites">

<% if @pets == nil || @pets == 0 %>
  <h4>No pets favorited.</h4>
<% else %>

  <% @pets.each do |pet| %>
    <section id= "pet-<%= pet.id %>">

      <img src=<%= pet.image %> alt="Dog pic" width="250">

      <h4>Name: <%= link_to "#{pet.name}", "/pets/#{pet.id}" %></h4>
      <%=  button_to "Remove from Favorites", "/favorites/#{pet.id}?remove=true", method: :patch %>
      <br>
    </section>
  <% end %>

<% end  %>
</section>
<% unless @pets == nil || @pets == 0 %>
  <%= link_to "Adopt!", "/adoptions/new", method: :get %>
<% end %>
<h3>Pets with Open Applications:</h3>
<section id= "pets_with_open_applications">
  <% @app_pets.uniq.each do |pet| %>
    <%= link_to "#{pet.name}", "/pets/#{pet.id}" %>
  <% end %>
</section>